name: bobofood
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  dio_cookie_manager: ^3.2.0
  dio_http2_adapter: ^2.6.0
  dismissible_page: ^1.0.2
  encrypt: ^5.0.3
  flutter_native_splash: ^2.4.4
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.8.0
  get: ^4.7.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  pull_to_refresh: ^2.0.0
  jiffy: ^6.3.2
  device_info_plus: ^10.1.2
  url_launcher: ^6.3.1
  logger: ^2.6.0
  connectivity_plus: ^6.1.4
  flutter_image_compress: ^2.4.0
  flutter_displaymode: ^0.6.0
  path: ^1.9.0
  flutter_launcher_icons: ^0.14.4
  carousel_slider: ^5.1.1
  flutter_svg: ^2.2.0
  pinput: ^5.0.1
  flutter_datetime_picker_plus: ^2.2.0
  uuid: ^4.5.1
  image_gallery_saver_plus: ^4.0.1
  wechat_camera_picker: ^4.3.7 # 相册
  wechat_assets_picker: ^9.5.1 # 摄像头
  device_preview: ^1.3.1
  event_bus: ^2.0.1
  flutter_local_notifications: ^19.3.1
  timezone: ^0.10.1
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png" # 你的图标路径
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/avatar.png
    - assets/background.png
    - assets/logo.png
    - assets/splash_logo.png
    - assets/splash.png
    - assets/splash_dark.png
    - assets/fonts/Poppins.ttf
    - assets/fonts/Roboto.ttf
    - assets/fonts/RobotoMono.ttf
    - assets/icons/
    - assets/images/
    - assets/tabbar/
    - assets/home/
    - assets/Illustrations/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono.ttf
